### ISSUE TITLE
Missing code for component LM5106_TRANS

### ISSUE THREAD

**Issue by ldrozd1977** [YetAnotherElectronicsChannel/Self-Oscillating-ClassD#1]
The code repository is missing the custom component "LM5106_TRANS" (for the power stage).

**Comment by YetAnotherElectronicsChannel** [comment]
The spice model can be downloaded directly from TI:
https://www.ti.com/lit/zip/snvmac8

I didn't want to share it over GitHub in order not to run into legal problems

**Comment by ldrozd1977** [comment]
Thanks!
